name: Azure SQL Backup Manager CI/CD (Terraform)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 22 * * *" # Run daily at 10 PM UTC

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          terraform init

  terraform_plan:
    needs: terraform_init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform plan -out=tfplan -var "sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}"

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform apply -auto-approve tfplan

      - name: Export Terraform Outputs to Environment
        id: export_outputs
        run: |
          set -e
          echo "Exporting Terraform Outputs..."

          RG_NAME=$(terraform output -raw resource_group_name)
          STORAGE_NAME=$(terraform output -raw storage_account_name)

          echo "RESOURCE_GROUP_NAME=$RG_NAME" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$STORAGE_NAME" >> $GITHUB_ENV

          echo "Terraform outputs exported successfully."

  nightly_backup:
    runs-on: ubuntu-latest
    environment: Production
    needs: terraform_apply
    if: github.event_name == 'schedule'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --name my-sql-backup-function \
            --src src/Backup-SqlDatabase.ps1

      - name: Set Environment Variables
        run: |
          az functionapp config appsettings set \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --name my-sql-backup-function \
            --settings STORAGE_ACCOUNT_NAME=${{ env.STORAGE_ACCOUNT_NAME }} \
                       STORAGE_ACCOUNT_KEY=${{ secrets.STORAGE_ACCOUNT_KEY }} \
                       CONTAINER_NAME=sql-backups

      - name: Run Backup Script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp run \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --name my-sql-backup-function \
              --function-name Backup-SqlDatabase

      - name: Run Cleanup Script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp run \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --name my-sql-backup-function \
              --function-name Remove-OldBackups
